import { bootstrapApplication } from '@angular/platform-browser';
import { isDevMode } from '@angular/core';
import { provideServiceWorker } from '@angular/service-worker';
import { RouteReuseStrategy, provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { defineCustomElements } from '@ionic/core/loader';
import { authInterceptor } from './app/interceptors/auth.interceptor';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { addIcons } from 'ionicons';
import { 
  closeOutline, 
  locationOutline, 
  power, 
  logOutOutline,
  logOut,
  arrowBack,
  arrowBackOutline,
  createOutline,
  personCircleOutline,
  personOutline,
  searchOutline,
  mapOutline,
  timeOutline,
  todayOutline,
  flashOutline,
  hourglassOutline,
  pulseOutline,
  logInOutline,
  personAdd,
  mailOutline,
  callOutline,
  cashOutline,
  shieldCheckmarkOutline,
  phonePortraitOutline,
  notificationsOutline,
  shareOutline,
  settingsOutline,
  informationCircleOutline,
  wifiOutline,
  wifi,
  checkmarkCircleOutline,
  closeCircleOutline,
  navigateOutline,
  calendarOutline,
  listOutline,
  trendingUpOutline,
  notificationsOffOutline,
  mailOpenOutline,
  chatbubbleOutline,
  alertCircle,
  chevronForwardOutline,
  chevronDownCircleOutline,
  flaskOutline,
  statsChartOutline,
  addCircleOutline,
  refreshOutline,
  saveOutline,
  homeOutline,
  documentTextOutline,
  businessOutline,
  hammerOutline,
  carOutline,
  medicalOutline,
  schoolOutline,
  restaurantOutline,
  constructOutline,
  briefcaseOutline,
  person,
  personCircle,
  location,
  eyeOutline,
  eyeOffOutline,
  lockClosedOutline,
  checkmarkCircle,
  closeCircle,
  starOutline,
  warningOutline,
  logoGoogle,
  logoWhatsapp
} from 'ionicons/icons';

addIcons({
  'close-outline': closeOutline,
  'location-outline': locationOutline,
  'power': power,
  'log-out-outline': logOutOutline,
  'log-out': logOut,
  'arrow-back': arrowBack,
  'arrow-back-outline': arrowBackOutline,
  'create-outline': createOutline,
  'person-circle-outline': personCircleOutline,
  'person-outline': personOutline,
  'search-outline': searchOutline,
  'map-outline': mapOutline,
  'time-outline': timeOutline,
  'today-outline': todayOutline,
  'flash-outline': flashOutline,
  'hourglass-outline': hourglassOutline,
  'pulse-outline': pulseOutline,
  'log-in-outline': logInOutline,
  'person-add': personAdd,
  'mail-outline': mailOutline,
  'call-outline': callOutline,
  'cash-outline': cashOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'phone-portrait-outline': phonePortraitOutline,
  'notifications-outline': notificationsOutline,
  'share-outline': shareOutline,
  'settings-outline': settingsOutline,
  'information-circle-outline': informationCircleOutline,
  'wifi-outline': wifiOutline,
  'wifi-off-outline': wifi,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'close-circle-outline': closeCircleOutline,
  'navigate-outline': navigateOutline,
  'calendar-outline': calendarOutline,
  'list-outline': listOutline,
  'trending-up-outline': trendingUpOutline,
  'notifications-off-outline': notificationsOffOutline,
  'mail-open-outline': mailOpenOutline,
  'chatbubble-outline': chatbubbleOutline,
  'alert-circle': alertCircle,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-down-circle-outline': chevronDownCircleOutline,
  'flask-outline': flaskOutline,
  'stats-chart-outline': statsChartOutline,
  'add-circle-outline': addCircleOutline,
  'refresh-outline': refreshOutline,
  'save-outline': saveOutline,
  'home-outline': homeOutline,
  'document-text-outline': documentTextOutline,
  'business-outline': businessOutline,
  'hammer-outline': hammerOutline,
  'car-outline': carOutline,
  'medical-outline': medicalOutline,
  'school-outline': schoolOutline,
  'restaurant-outline': restaurantOutline,
  'construct-outline': constructOutline,
  'briefcase-outline': briefcaseOutline,
  'person': person,
  'person-circle': personCircle,
  'location': location,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'lock-closed-outline': lockClosedOutline,
  'checkmark-circle': checkmarkCircle,
  'close-circle': closeCircle,
  'star-outline': starOutline,
  'warning-outline': warningOutline,
  'logo-google': logoGoogle,
  'logo-whatsapp': logoWhatsapp
});

if (typeof window !== 'undefined') {
  defineCustomElements(window);
}

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(
      withInterceptors([authInterceptor])
    ),
    // Registers the Angular Service Worker in production so the app can be
    // installed as a PWA and receive Web Push notifications. Waits 30s
    // after stability so it doesn't compete with initial hydration.
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000'
    }),
  ],
});
